# Generated by Django 6.0.4 on 2026-05-03 13:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('staff', 'UFAA Staff'), ('admin', 'Administrator'), ('agent', 'Agent')], default='citizen', max_length=20)),
                ('no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('residence', models.CharField(blank=True, choices=[('', 'Blank'), ('Kenyan', 'Kenyan'), ('Non_Kenyan', 'Non Kenyan')], default='', max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('iprs_name', models.CharField(blank=True, max_length=200)),
                ('claimant_birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('', 'Blank'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10)),
                ('person_living_with_disability', models.BooleanField(default=False)),
                ('passport_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('business_registration_no', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('address_2', models.TextField(blank=True)),
                ('phone_no', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+25412345678'", regex='^\\+?1?\\d{9,15}$')])),
                ('secondary_phone_no', models.CharField(blank=True, max_length=17)),
                ('post_code', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('home_county', models.CharField(blank=True, max_length=50)),
                ('e_mail', models.EmailField(blank=True, max_length=254)),
                ('county_code', models.CharField(blank=True, max_length=20)),
                ('county_name', models.CharField(blank=True, max_length=100)),
                ('gps_location', models.JSONField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('initiator', 'Initiator'), ('document_verification', 'Document Verification'), ('examiner', 'Examiner'), ('authorizer', 'Authorizer'), ('publisher', 'Publisher'), ('executive_officer', 'Executive Officer'), ('finance', 'Finance')], max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('profile_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id_number'], name='users_id_numb_b4b92a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_no'], name='users_phone_n_b44fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['passport_no'], name='users_passpor_ed3827_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['no'], name='users_no_b33244_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
    ]
