# Generated by Django 6.0.4 on 2026-05-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disability_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='disability_certificate_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
