# Generated by Django 6.0.4 on 2026-05-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_missing_fields2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disability_category',
            field=models.CharField(blank=True, choices=[('physical', 'Physical Disability'), ('visual', 'Visual Impairment'), ('hearing', 'Hearing Impairment'), ('speech', 'Speech Impairment'), ('intellectual', 'Intellectual Disability'), ('mental', 'Mental Health Condition'), ('learning', 'Learning Disability'), ('multiple', 'Multiple Disabilities'), ('albinism', 'Albinism'), ('other', 'Other')], max_length=100),
        ),
    ]
