# Generated by Django 6.0.4 on 2026-05-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_disability_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='Kenyan National ID Card Number (8 digits)', max_length=9, null=True, unique=True, verbose_name='National ID Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_no',
            field=models.CharField(blank=True, help_text='For non-Kenyan residents', max_length=20, null=True, unique=True, verbose_name='Passport Number'),
        ),
    ]
