# Generated by Django 6.0.4 on 2026-05-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loginhistory_userdevice_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('register', 'Registration'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('claim_submit', 'Claim Submitted'), ('document_upload', 'Document Uploaded')], max_length=50),
        ),
    ]
