# Generated by Django 6.0.4 on 2026-06-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_useractivitylog_activity_type'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_verification_code',
            field=models.CharField(blank=True, help_text='6-digit code for manual email verification', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when verification email was last sent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when email was verified', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Designates whether the user's email has been verified."),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification link', max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('register', 'Registration'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('claim_submit', 'Claim Submitted'), ('document_upload', 'Document Uploaded'), ('email_verify', 'Email Verified'), ('verification_resend', 'Verification Email Resent')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='users_is_veri_63cd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['verification_token'], name='users_verific_ccfceb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['verification_sent_at'], name='users_verific_1c4141_idx'),
        ),
    ]
