# Generated by Django 6.0.4 on 2026-06-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_temporary_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
