# Generated by Django 6.0.4 on 2026-06-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_reset_token_user_reset_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
