# Generated by Django 6.0.4 on 2026-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_reset_token'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id_number', models.CharField(blank=True, max_length=9)),
                ('phone_no', models.CharField(blank=True, max_length=17)),
                ('reason', models.CharField(blank=True, choices=[('no_longer_needed', 'No longer needed'), ('privacy_concerns', 'Privacy concerns'), ('duplicate_account', 'Duplicate account'), ('created_by_mistake', 'Created by mistake'), ('too_many_emails', 'Too many emails/notifications'), ('switching_service', 'Switching to another service'), ('other', 'Other')], max_length=50)),
                ('reason_details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account_deletion_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the account was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', help_text='Reason code provided at deletion time.', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_reason_details',
            field=models.TextField(blank=True, default='', help_text='Free-text explanation provided by the user.'),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which deletion was requested.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether the user has deleted their account.'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('register', 'Registration'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('claim_submit', 'Claim Submitted'), ('document_upload', 'Document Uploaded'), ('email_verify', 'Email Verified'), ('verification_resend', 'Verification Email Resent'), ('account_delete', 'Account Deleted')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='users_is_dele_21b557_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at'], name='users_deleted_e48316_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['user_id'], name='account_del_user_id_1023ff_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['email'], name='account_del_email_5b8380_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['requested_at'], name='account_del_request_ed6b5c_idx'),
        ),
    ]
