# Generated by Django 6.0.4 on 2026-09-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_accountdeletionrequest_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', help_text='Reason code provided at deletion time.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deletion_reason_details',
            field=models.TextField(blank=True, default='', help_text='Free-text explanation provided by the user.', null=True),
        ),
    ]
