# Generated by Django 6.0.4 on 2026-09-20 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_deletion_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+25412345678'", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
