# Generated by Django 6.0.4 on 2026-09-20 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(db_index=True, help_text='Asset number from the live Unclaimed Asset table', max_length=100)),
                ('asset_name', models.CharField(blank=True, max_length=255)),
                ('asset_owner', models.CharField(blank=True, max_length=255)),
                ('holder_name', models.CharField(blank=True, max_length=255)),
                ('holder_no', models.CharField(blank=True, max_length=100)),
                ('asset_type', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('id_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('passport_no', models.CharField(blank=True, db_index=True, max_length=50)),
                ('cds_account_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('postal_address', models.CharField(blank=True, max_length=500)),
                ('city_town', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('found', 'Found'), ('not_found', 'Not Found'), ('moved', 'Moved'), ('transferred', 'Transferred')], default='pending', max_length=20)),
                ('last_notes', models.TextField(blank=True)),
                ('staff_email', models.EmailField(db_index=True, max_length=254)),
                ('staff_name', models.CharField(blank=True, max_length=255)),
                ('last_tracked_at', models.DateTimeField(blank=True, null=True)),
                ('last_tracked_by', models.CharField(blank=True, max_length=255)),
                ('last_staff_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('last_staff_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracked_assets',
                'ordering': ['-last_tracked_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTrackingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('photo', 'Photo of Asset'), ('form', 'Completed Form'), ('receipt', 'Receipt'), ('letter', 'Letter'), ('id', 'Identification'), ('other', 'Other')], default='photo', max_length=20)),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(max_length=500, upload_to='asset_tracking/%Y/%m/%d/')),
                ('file_size', models.IntegerField(default=0)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('uploaded_by_email', models.EmailField(blank=True, max_length=254)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_tracking_documents', to=settings.AUTH_USER_MODEL)),
                ('tracked_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='asset_tracking.trackedasset')),
            ],
            options={
                'db_table': 'asset_tracking_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('staff_email', models.EmailField(db_index=True, max_length=254)),
                ('staff_name', models.CharField(blank=True, max_length=255)),
                ('staff_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('staff_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tracked_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='asset_tracking.trackedasset')),
            ],
            options={
                'db_table': 'asset_location_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackedasset',
            index=models.Index(fields=['asset_no'], name='tracked_ass_asset_n_e54cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedasset',
            index=models.Index(fields=['staff_email'], name='tracked_ass_staff_e_bc31b7_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedasset',
            index=models.Index(fields=['id_number'], name='tracked_ass_id_numb_267c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedasset',
            index=models.Index(fields=['passport_no'], name='tracked_ass_passpor_c86431_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedasset',
            index=models.Index(fields=['cds_account_no'], name='tracked_ass_cds_acc_cb5880_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedasset',
            index=models.Index(fields=['status'], name='tracked_ass_status_0ad242_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedasset',
            index=models.Index(fields=['last_tracked_at'], name='tracked_ass_last_tr_0f5519_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackedasset',
            unique_together={('asset_no', 'staff_email')},
        ),
    ]
