# Generated by Django 6.0.4 on 2026-09-21 14:16

import storage.sharepoint
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettrackingdocument',
            name='storage_backend',
            field=models.CharField(default='sharepoint', editable=False, help_text='Which storage backend holds the file bytes.', max_length=50),
        ),
        migrations.AlterField(
            model_name='assettrackingdocument',
            name='file',
            field=models.FileField(help_text='Upload the document file (stored on SharePoint)', max_length=500, storage=storage.sharepoint.SharePointStorage(), upload_to='asset_tracking/%Y/%m/%d/'),
        ),
    ]
