# Generated by Django 6.0.4 on 2026-09-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IprsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ID Card Number')),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('iprs_id', models.IntegerField(blank=True, null=True, verbose_name='IPRS Internal ID')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Raw Response')),
                ('is_valid', models.BooleanField(default=True, help_text='False if the ID was not found in IPRS', verbose_name='Is Valid')),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'IPRS Cache Entry',
                'verbose_name_plural': 'IPRS Cache Entries',
                'db_table': 'iprs_cache',
                'ordering': ['-cached_at'],
            },
        ),
        migrations.CreateModel(
            name='IprsSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(db_index=True, help_text='National ID number that was searched', max_length=20, verbose_name='ID Card Number')),
                ('requested_from_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Request IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, verbose_name='Device Fingerprint')),
                ('status', models.CharField(choices=[('success', 'Success'), ('not_found', 'Not Found'), ('error', 'Error'), ('rate_limited', 'Rate Limited'), ('timeout', 'Timeout')], db_index=True, default='error', max_length=20)),
                ('response_data', models.JSONField(blank=True, help_text='Full response from IPRS API', null=True, verbose_name='Response Data')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('iprs_id', models.IntegerField(blank=True, null=True, verbose_name='IPRS Internal ID')),
                ('searched_at', models.DateTimeField(blank=True, null=True, verbose_name='IPRS Searched At')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Response Time (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'IPRS Search Log',
                'verbose_name_plural': 'IPRS Search Logs',
                'db_table': 'iprs_search_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_card', '-created_at'], name='iprs_search_id_card_08e94e_idx'), models.Index(fields=['status', '-created_at'], name='iprs_search_status_42976b_idx'), models.Index(fields=['requested_from_ip', '-created_at'], name='iprs_search_request_0624c4_idx'), models.Index(fields=['created_at'], name='iprs_search_created_cf65d6_idx')],
            },
        ),
    ]
