# Generated by Django 6.0.4 on 2026-05-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDocumentReference',
            fields=[
                ('doc_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('claim_no', models.CharField(db_column='Claim No', max_length=100)),
                ('document_type', models.CharField(db_column='Document Type', max_length=50)),
                ('file_name', models.CharField(db_column='File Name', max_length=500)),
                ('sharepoint_url', models.CharField(db_column='SharePoint URL', max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, db_column='File Size', null=True)),
                ('uploaded_by', models.CharField(blank=True, db_column='Uploaded By', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='Uploaded At')),
            ],
            options={
                'db_table': '"UFAA TRUST FUND$Claim Documents$2636ffcf-1aea-4b3a-808a-c1da12e824c1"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiveOnlineClaim',
            fields=[
                ('claim_no', models.CharField(db_column='Claim No', max_length=100, primary_key=True, serialize=False)),
                ('document_date', models.DateField(blank=True, db_column='Document Date', null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('claim_type', models.CharField(blank=True, db_column='Claim Type', max_length=50, null=True)),
                ('claimant_name', models.CharField(db_column='Claimant Name', max_length=200)),
                ('claimant_id', models.CharField(db_column='Claimant ID', db_index=True, max_length=50)),
                ('claimant_phone', models.CharField(blank=True, db_column='Claimant Phone', max_length=20, null=True)),
                ('claimant_email', models.EmailField(blank=True, db_column='Claimant Email', max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(db_column='Status', default='Pending', max_length=50)),
                ('payment_category', models.CharField(blank=True, db_column='Payment Category', max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, db_column='Bank Name', max_length=200, null=True)),
                ('bank_account_no', models.CharField(blank=True, db_column='Bank Account No', max_length=50, null=True)),
                ('mpesa_mobile_no', models.CharField(blank=True, db_column='Mpesa Mobile No', max_length=20, null=True)),
                ('cds_account_no', models.CharField(blank=True, db_column='CDS Account No', max_length=50, null=True)),
                ('claimant_passport', models.CharField(blank=True, db_column='Claimant Passport', db_index=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Updated At')),
            ],
            options={
                'db_table': '"UFAA TRUST FUND$Online Claim$2636ffcf-1aea-4b3a-808a-c1da12e824c1"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiveOnlineClaimLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_no', models.IntegerField(db_column='Line No')),
                ('asset_no', models.CharField(blank=True, db_column='Asset No', max_length=100, null=True)),
                ('asset_type', models.CharField(blank=True, db_column='Asset Type', max_length=50, null=True)),
                ('asset_value', models.DecimalField(blank=True, db_column='Asset Value', decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('holder_name', models.CharField(blank=True, db_column='Holder Name', max_length=200, null=True)),
                ('document_path', models.CharField(blank=True, db_column='Document Path', max_length=500, null=True)),
            ],
            options={
                'db_table': '"UFAA TRUST FUND$Online Claim Lines$2636ffcf-1aea-4b3a-808a-c1da12e824c1"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiveUnclaimedAsset',
            fields=[
                ('asset_no', models.CharField(db_column='Asset No', max_length=100, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(db_column='Owner Name', max_length=200)),
                ('owner_id', models.CharField(db_column='Owner ID', db_index=True, max_length=50)),
                ('holder_name', models.CharField(db_column='Holder Name', max_length=200)),
                ('asset_type', models.CharField(blank=True, db_column='Asset Type', max_length=50, null=True)),
                ('value', models.DecimalField(blank=True, db_column='Value', decimal_places=2, max_digits=15, null=True)),
                ('physical_address', models.TextField(blank=True, db_column='Physical Address', null=True)),
                ('status', models.CharField(db_column='Status', default='available', max_length=50)),
                ('is_claimed', models.BooleanField(db_column='Is Claimed', default=False)),
                ('reported_date', models.DateField(blank=True, db_column='Reported Date', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='Last Updated')),
                ('cds_account_no', models.CharField(blank=True, db_column='CDS Account No', db_index=True, max_length=50, null=True)),
                ('passport_no', models.CharField(blank=True, db_column='Passport No', db_index=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"UFAA TRUST FUND$Unclaimed Asset$2636ffcf-1aea-4b3a-808a-c1da12e824c1"',
                'managed': False,
            },
        ),
    ]
