# Generated by Django 6.0.4 on 2026-06-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveunclaimedasset',
            options={'managed': False, 'ordering': ['-timestamp']},
        ),
        migrations.AlterModelTable(
            name='livedocumentreference',
            table='[UFAA TRUST FUND$Claim Documents$2636ffcf-1aea-4b3a-808a-c1da12e824c1]',
        ),
        migrations.AlterModelTable(
            name='liveonlineclaim',
            table='[UFAA TRUST FUND$Online Claim$2636ffcf-1aea-4b3a-808a-c1da12e824c1]',
        ),
        migrations.AlterModelTable(
            name='liveonlineclaimline',
            table='[UFAA TRUST FUND$Online Claim Lines$2636ffcf-1aea-4b3a-808a-c1da12e824c1]',
        ),
        migrations.AlterModelTable(
            name='liveunclaimedasset',
            table='[UFAA TRUST FUND$Unclaimed Asset$2636ffcf-1aea-4b3a-808a-c1da12e824c1]',
        ),
    ]
