# Generated by Django 6.0.4 on 2026-06-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_operations', '0002_alter_liveunclaimedasset_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveonlineclaim',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
