# Generated by Django 6.0.4 on 2026-09-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_operations', '0003_alter_liveonlineclaim_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Logical name for the sync job (e.g. 'rejected_claims').", max_length=100, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When the job last started.', null=True)),
                ('last_success_at', models.DateTimeField(blank=True, help_text='When the job last completed successfully.', null=True)),
                ('last_error', models.TextField(blank=True, default='', help_text='Last error message, if any.')),
            ],
            options={
                'db_table': 'live_sync_state',
                'ordering': ['name'],
            },
        ),
    ]
