# apps/iprs/admin.py
from django.contrib import admin
from django.utils import timezone
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _

from .models import IprsCache, IprsSearchLog


@admin.register(IprsSearchLog)
class IprsSearchLogAdmin(admin.ModelAdmin):
    """
    Admin configuration for IPRS Search Logs.
    Read-only audit log configuration to prevent manual tampering.
    """
    list_display = [
        'created_at',
        'id_card',
        'get_full_name',
        'status_badge',
        'requested_from_ip',
        'response_time_ms',
    ]
    list_filter = [
        'status',
        'created_at',
        'gender',
    ]
    search_fields = [
        'id_card',
        'surname',
        'other_names',
        'requested_from_ip',
        'device_fingerprint',
    ]
    readonly_fields = [
        'id_card',
        'requested_from_ip',
        'user_agent',
        'device_fingerprint',
        'status',
        'response_data',
        'error_message',
        'surname',
        'other_names',
        'gender',
        'iprs_id',
        'searched_at',
        'response_time_ms',
        'created_at',
    ]
    date_hierarchy = 'created_at'
    list_per_page = 50

    fieldsets = (
        (_('Search & Requester Info'), {
            'fields': (
                'id_card',
                'status',
                'requested_from_ip',
                'user_agent',
                'device_fingerprint',
            )
        }),
        (_('Extracted Personal Details'), {
            'fields': (
                'surname',
                'other_names',
                'gender',
                'iprs_id',
                'searched_at',
            )
        }),
        (_('API Response & Performance'), {
            'fields': (
                'response_time_ms',
                'created_at',
                'error_message',
                'response_data',
            ),
            'classes': ('collapse',),
        }),
    )

    @admin.display(description=_('Full Name'))
    def get_full_name(self, obj):
        return obj.full_name or "-"

    @admin.display(description=_('Status'), ordering='status')
    def status_badge(self, obj):
        colors = {
            'success': '#10B981',      # Emerald Green
            'not_found': '#F59E0B',    # Amber
            'error': '#EF4444',        # Red
            'rate_limited': '#8B5CF6', # Purple
            'timeout': '#6B7280',     # Gray
        }
        color = colors.get(obj.status, '#6B7280')
        return format_html(
            '<span style="background-color: {}; color: white; padding: 3px 8px; '
            'border-radius: 4px; font-weight: bold; font-size: 11px;">{}</span>',
            color,
            obj.get_status_display()
        )

    def has_add_permission(self, request):
        # Audit logs are generated by the system, not manually added
        return False

    def has_delete_permission(self, request, obj=None):
        # Prevent manual deletion from admin unless superuser explicitly allowed
        return request.user.is_superuser


class ExpiredListFilter(admin.SimpleListFilter):
    """Custom filter to check expired state on IprsCache entries."""
    title = _('Expiration Status')
    parameter_name = 'expired'

    def lookups(self, request, model_admin):
        return (
            ('active', _('Active (Not Expired)')),
            ('expired', _('Expired')),
        )

    def queryset(self, request, queryset):
        now = timezone.now()
        if self.value() == 'active':
            return queryset.filter(expires_at__gte=now)
        if self.value() == 'expired':
            return queryset.filter(expires_at__lt=now)
        return queryset


@admin.register(IprsCache)
class IprsCacheAdmin(admin.ModelAdmin):
    """Admin configuration for managing cached IPRS response entries."""
    list_display = [
        'id_card',
        'get_full_name',
        'is_valid',
        'is_expired_status',
        'cached_at',
        'expires_at',
    ]
    list_filter = [
        'is_valid',
        ExpiredListFilter,
        'gender',
        'cached_at',
    ]
    search_fields = [
        'id_card',
        'surname',
        'other_names',
    ]
    readonly_fields = ['cached_at']
    actions = ['cleanup_all_expired', 'invalidate_selected_entries']
    list_per_page = 50

    fieldsets = (
        (_('Identity Details'), {
            'fields': (
                'id_card',
                'surname',
                'other_names',
                'gender',
                'iprs_id',
            )
        }),
        (_('Cache Control'), {
            'fields': (
                'is_valid',
                'cached_at',
                'expires_at',
            )
        }),
        (_('Raw API Response'), {
            'fields': ('raw_response',),
            'classes': ('collapse',),
        }),
    )

    @admin.display(description=_('Full Name'))
    def get_full_name(self, obj):
        return obj.full_name or "-"

    @admin.display(description=_('Expired'), boolean=True)
    def is_expired_status(self, obj):
        return obj.is_expired

    @admin.action(description=_('Cleanup all expired cache entries in system'))
    def cleanup_all_expired(self, request, queryset):
        deleted_count = IprsCache.cleanup_expired()
        self.message_user(request, f"Successfully deleted {deleted_count} expired cache records.")

    @admin.action(description=_('Mark selected cache entries as invalid'))
    def invalidate_selected_entries(self, request, queryset):
        updated = queryset.update(is_valid=False)
        self.message_user(request, f"Marked {updated} cache records as invalid.")
