# Generated by Django 6.0.4 on 2026-05-10 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0006_alter_claim_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePointDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=500)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(choices=[('claim_form', 'Claim Form'), ('indemnity_form', 'Indemnity Agreement'), ('id_copy', 'ID Copy'), ('kra_pin', 'KRA PIN Certificate'), ('death_certificate', 'Death Certificate'), ('grant_certificate', 'Grant Certificate'), ('holder_letter', 'Holder Letter'), ('bank_statement', 'Bank Statement'), ('payment_form', 'Payment Form'), ('affidavit', 'Affidavit'), ('power_of_attorney', 'Power of Attorney'), ('guardianship_deed', 'Guardianship Deed'), ('cr12', 'CR12 Form'), ('incorporation', 'Certificate of Incorporation'), ('other', 'Other')], max_length=50)),
                ('sharepoint_site', models.CharField(max_length=500)),
                ('sharepoint_library', models.CharField(max_length=200)),
                ('sharepoint_folder', models.CharField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharepoint_documents', to='claims.claim')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sharepoint_docs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sharepoint_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sharepoint_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_id'], name='sharepoint__file_id_71e42e_idx'), models.Index(fields=['claim', 'document_type'], name='sharepoint__claim_i_75cac1_idx'), models.Index(fields=['created_at'], name='sharepoint__created_f52e63_idx')],
            },
        ),
    ]
