# Generated by Django 6.0.4 on 2026-05-03 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=50, unique=True)),
                ('asset_type', models.CharField(blank=True, choices=[('', 'Blank'), ('Cash', 'Cash'), ('Non_Cash', 'Non_Cash')], default='', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('', 'Blank'), ('Cash', 'Cash'), ('Shares', 'Shares'), ('Safe_Deposit', 'Safe Deposit')], default='', max_length=20)),
                ('class_code', models.CharField(blank=True, max_length=50)),
                ('class_field', models.CharField(blank=True, choices=[('', 'Blank'), ('Account_Balances', 'Account Balances'), ('Uncashed_Cheques', 'Uncashed Cheques'), ('Safe_Deposit_Boxes__x0026__Safe_Keeping', 'Safe Deposit Boxes & Safe Keeping'), ('Insurance', 'Insurance'), ('Government_Assets', 'Government Assets'), ('Misc_Cheques__x0026__Intangible_Property', 'Misc Cheques & Intangible Property'), ('Securities', 'Securities'), ('Utilities', 'Utilities'), ('Trust__x0026__Escrow_Accounts', 'Trust & Escrow Accounts')], db_column='class', max_length=50)),
                ('asset_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('description_field', models.TextField(blank=True, db_column='description_')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('holder_no', models.CharField(blank=True, max_length=50)),
                ('holder_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('passport_no', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('owners_postal_address', models.TextField(blank=True)),
                ('owners_city_town', models.CharField(blank=True, max_length=100)),
                ('owners_telephone_no', models.CharField(blank=True, max_length=20)),
                ('interest_bearing_account', models.BooleanField(default=False)),
                ('more_than_one_owner', models.BooleanField(default=False)),
                ('item_no', models.IntegerField(blank=True, null=True)),
                ('description_of_the_content', models.TextField(blank=True)),
                ('value_of_the_content', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('safe_deposit_no', models.CharField(blank=True, max_length=50)),
                ('no_of_remitted_shares', models.IntegerField(blank=True, null=True)),
                ('cds_account_no', models.CharField(blank=True, max_length=50)),
                ('cheque_no', models.CharField(blank=True, max_length=50)),
                ('amount_due_to_owner', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50)),
                ('currency_code', models.CharField(blank=True, max_length=10)),
                ('drawee', models.CharField(blank=True, max_length=200)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('drawee_id_number', models.CharField(blank=True, max_length=20)),
                ('physical_address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('synchronized', models.BooleanField(default=False)),
                ('batch_no', models.CharField(blank=True, max_length=50)),
                ('line_no', models.IntegerField(blank=True, null=True)),
                ('asset_appl_no', models.CharField(blank=True, max_length=50)),
                ('document_line_no', models.IntegerField(blank=True, null=True)),
                ('base_unit_of_measure', models.CharField(blank=True, max_length=20)),
                ('value_lcy', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('posted', models.BooleanField(default=False)),
                ('location_source', models.CharField(blank=True, max_length=50)),
                ('reported_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.TextField(blank=True)),
                ('building_name', models.CharField(blank=True, max_length=200)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('additional_instructions', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('found', 'Found'), ('not_found', 'Not Found'), ('transferred', 'Transferred'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('location_source', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='assets.asset')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_locations',
            },
        ),
        migrations.CreateModel(
            name='AssetTrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='assets.asset')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_tracking_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['id_number'], name='assets_id_numb_c22ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_no'], name='assets_asset_n_118e54_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['holder_name'], name='assets_holder__cd4a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_status_326766_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlocation',
            index=models.Index(fields=['status'], name='asset_locat_status_bd301c_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='asset_locat_latitud_25e6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='assettrackinghistory',
            index=models.Index(fields=['asset'], name='asset_track_asset_i_4d9c54_idx'),
        ),
        migrations.AddIndex(
            model_name='assettrackinghistory',
            index=models.Index(fields=['-created_at'], name='asset_track_created_080660_idx'),
        ),
    ]
