# Generated by Django 6.0.4 on 2026-05-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_options_remove_claim_address_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='has_joint_owners',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_joint_bank_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='joint_bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='joint_bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='joint_bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='joint_owners_consent_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='joint_owners_consent_status',
            field=models.CharField(default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='joint_owners_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='no_objection_letter_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='claim',
            name='no_objection_letter_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='no_objection_letter_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='no',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='JointOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('id_number', models.CharField(max_length=20)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationality', models.CharField(choices=[('Kenyan', 'Kenyan'), ('Non_Kenyan', 'Non-Kenyan')], default='Kenyan', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_address', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_category', models.CharField(blank=True, max_length=100)),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_primary_claimant', models.BooleanField(default=False)),
                ('has_consented', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('consent_form_uploaded', models.BooleanField(default=False)),
                ('consent_form_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_owners', to='claims.claim')),
            ],
            options={
                'db_table': 'joint_owners',
            },
        ),
        migrations.CreateModel(
            name='JointOwnerConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('consent_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_owner_consents', to='claims.claim')),
                ('joint_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='claims.jointowner')),
            ],
            options={
                'db_table': 'joint_owner_consents',
            },
        ),
        migrations.CreateModel(
            name='JointPaymentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('single', 'Pay to Primary Claimant'), ('split', 'Split Among Joint Owners'), ('joint_account', 'Pay to Joint Account'), ('nominee', 'Nominate One Owner')], default='single', max_length=20)),
                ('split_percentages', models.JSONField(blank=True, default=dict)),
                ('joint_account_name', models.CharField(blank=True, max_length=200)),
                ('joint_account_number', models.CharField(blank=True, max_length=50)),
                ('joint_bank_name', models.CharField(blank=True, max_length=200)),
                ('joint_branch_name', models.CharField(blank=True, max_length=200)),
                ('nominee_owner_id', models.IntegerField(blank=True, null=True)),
                ('nominee_consent_received', models.BooleanField(default=False)),
                ('no_objection_letter_path', models.CharField(blank=True, max_length=500)),
                ('joint_consent_form_path', models.CharField(blank=True, max_length=500)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joint_payment_instruction', to='claims.claim')),
            ],
            options={
                'db_table': 'joint_payment_instructions',
            },
        ),
        migrations.AddIndex(
            model_name='jointowner',
            index=models.Index(fields=['claim', 'id_number'], name='joint_owner_claim_i_bd9597_idx'),
        ),
        migrations.AddIndex(
            model_name='jointowner',
            index=models.Index(fields=['id_number'], name='joint_owner_id_numb_ecc701_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jointowner',
            unique_together={('claim', 'id_number')},
        ),
        migrations.AddIndex(
            model_name='jointownerconsent',
            index=models.Index(fields=['consent_token'], name='joint_owner_consent_e085e3_idx'),
        ),
        migrations.AddIndex(
            model_name='jointownerconsent',
            index=models.Index(fields=['status'], name='joint_owner_status_7c1a04_idx'),
        ),
    ]
