# Generated by Django 6.0.4 on 2026-05-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claim_has_joint_owners_claim_is_joint_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='joint_owners_count',
        ),
        migrations.AddField(
            model_name='claim',
            name='address_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='address_to_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='address_to_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='business_owner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='cause_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='date_signed_by_hod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='doc_verification_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='donee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='donor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='entry_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='estate_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='issuing_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='name_of_deceased',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='postal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='rpa_ipa_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='serial_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='title_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='type_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claim',
            name='type_field',
            field=models.CharField(blank=True, db_column='type', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='verification_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claimasset',
            name='broker_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claimasset',
            name='broker_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='claimasset',
            name='cds_account_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claimasset',
            name='stock_exchange',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='document_type',
            field=models.CharField(choices=[('form4a', 'Form 4A - Original Owner Claim'), ('form4b', 'Form 4B - Beneficiary Claim'), ('form4c', 'Form 4C - Business Entity Claim'), ('form4d', 'Form 4D - Agent Claim'), ('form5', 'Form 5 - Indemnity Agreement'), ('id_copy', 'Certified ID Copy'), ('kra_pin', 'KRA PIN Certificate'), ('death_certificate', 'Death Certificate'), ('grant_certificate', 'Certificate of Confirmation of Grant'), ('holder_letter', 'Holder Confirmation Letter'), ('bank_statement', 'Bank/M-Pesa Statement'), ('affidavit', 'Original Affidavit'), ('policy_document', 'Policy Document'), ('power_of_attorney', 'Power of Attorney'), ('guardianship_deed', 'Guardianship Deed'), ('cr12', 'CR12 Form'), ('incorporation', 'Certificate of Incorporation'), ('directors_ids', 'Directors ID Copies'), ('payment_form', 'Payment Form'), ('other', 'Other Document')], max_length=50),
        ),
    ]
