# Generated by Django 6.0.4 on 2026-05-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_remove_claim_joint_owners_count_claim_address_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimasset',
            name='broker_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claimasset',
            name='broker_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='claimasset',
            name='cds_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claimasset',
            name='stock_exchange',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
