# Generated by Django 6.0.4 on 2026-05-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claimasset_broker_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
