# Generated by Django 6.0.4 on 2026-05-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_alter_claim_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claimant_birth_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
