# Generated by Django 6.0.4 on 2026-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_alter_claim_claimant_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='no',
            field=models.CharField(blank=True, db_index=True, help_text='Claim number generated by mobile app (Format: CLM-{IDENTIFIER}-{TIMESTAMP})', max_length=100, unique=True),
        ),
    ]
