# Generated by Django 6.0.4 on 2026-06-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_alter_claim_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='no',
            field=models.CharField(blank=True, db_index=True, help_text='Claim number generated by mobile app (Format: CM-{random_suffix}{TIMESTAMP})', max_length=100, unique=True),
        ),
    ]
