# Generated by Django 6.0.4 on 2026-06-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_alter_claim_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='claim',
            name='claimant',
            field=models.ForeignKey(blank=True, help_text='User who owns this claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='no',
            field=models.CharField(blank=True, db_index=True, help_text='Claim number generated by mobile app (Format: CM{random_suffix}{TIMESTAMP})', max_length=100, unique=True),
        ),
    ]
