# Generated by Django 6.0.4 on 2026-06-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_remove_claim_user_id_alter_claim_claimant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
