# Generated by Django 6.0.4 on 2026-06-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_claim_completed_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='claimasset',
            name='claim_asset_claim_i_6efbe4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='claimasset',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='claimasset',
            name='asset_no',
            field=models.CharField(blank=True, db_index=True, help_text='Asset number from live database', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='claimasset',
            index=models.Index(fields=['claim', 'asset_no'], name='claim_asset_claim_i_ca7566_idx'),
        ),
        migrations.RemoveField(
            model_name='claimasset',
            name='asset',
        ),
    ]
