# Generated by Django 6.0.4 on 2026-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_remove_claimasset_claim_asset_claim_i_6efbe4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Upload the document file', max_length=500, null=True, upload_to='claim_documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='document_type',
            field=models.CharField(choices=[('combined', 'All Forms Combined'), ('form4a', 'Form 4A - Original Owner Claim'), ('form4b', 'Form 4B - Beneficiary Claim'), ('form4c', 'Form 4C - Business Entity Claim'), ('form4d', 'Form 4D - Agent Claim'), ('form5', 'Form 5 - Indemnity Agreement'), ('id_copy', 'Certified ID Copy'), ('kra_pin', 'KRA PIN Certificate'), ('death_certificate', 'Death Certificate'), ('grant_certificate', 'Certificate of Confirmation of Grant'), ('holder_letter', 'Holder Confirmation Letter'), ('bank_statement', 'Bank/M-Pesa Statement'), ('affidavit', 'Original Affidavit'), ('policy_document', 'Policy Document'), ('power_of_attorney', 'Power of Attorney'), ('guardianship_deed', 'Guardianship Deed'), ('cr12', 'CR12 Form'), ('incorporation', 'Certificate of Incorporation'), ('directors_ids', 'Directors ID Copies'), ('payment_form', 'Payment Form'), ('other', 'Other Document')], max_length=50),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='file_path',
            field=models.CharField(blank=True, help_text='Legacy field - use file instead', max_length=500),
        ),
    ]
