# Generated by Django 6.0.4 on 2026-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_claimdocument_file_alter_claimdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_origin',
            field=models.CharField(blank=True, choices=[('', 'Blank'), ('WhatsApp', 'WhatsApp'), ('OnlinePortal', 'Online Portal'), ('Android_Mobile_App', 'Android Mobile App'), ('iOS_Mobile_App', 'iOS Mobile App'), ('Reception', 'Reception'), ('Emails', 'Emails'), ('Reunification_Clinics', 'Reunification Clinics'), ('Huduma', 'Huduma'), ('Registrars', 'Registrars')], default='', max_length=30),
        ),
    ]
