# Generated by Django 6.0.4 on 2026-09-21 14:16

import storage.sharepoint
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_alter_claim_claim_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdocument',
            name='storage_backend',
            field=models.CharField(default='sharepoint', editable=False, help_text='Which storage backend holds the file bytes.', max_length=50),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Upload the document file (stored on SharePoint)', max_length=500, null=True, storage=storage.sharepoint.SharePointStorage(), upload_to='claim_documents/%Y/%m/%d/'),
        ),
    ]
